<h2>Editor de Aldeias</h2>
{if $result neq ""}
	<h3>{$result|replace:"Änderungen erfolgreich.":"Ação"}</h3>
	<p>A Aldeia Foi Editada Com Sucesso! Agora Para Terminar Você Deve Atializar a Classificação. <a href="index.php?screen=recalc&run">CLIKE AKI</a></p>
{/if}
<h4>Selecionando Aldeia</h4>
<form action="index.php?screen=village_editor&amp;action=edit" method="POST">
Escolha aqui a aldeia que deseja alterar: 
<select name="name">
{foreach from=$v item=village}
	<option value="{$village.name|urldecode}">{$village.name|urldecode}</option>
{foreachelse}
	<option value="">-- Não existe aldeias no jogo</option>
{/foreach}
</select> 
<br><br>
Lembre-se todas as aldeias com o mesmo nome serão afetadas.
<br>
<table class="vis">
	<tr>
		<th>Edifício</th>
		<th>Nivel*</th>
	</tr>
	{foreach from=$needed key=name item=dbname}
	<tr>
		<td><img src="../graphic/buildings/{$dbname}.png"> {$name}</td>
		<td><input name="{$dbname}" id="{$dbname}" type="text" size="5" value="na" style="text-align:center;border:1px solid #804000;background-color:#F8F4E8;" /></td>
	</tr>
	{/foreach}
	<tr>
		<td colspan="2">
		<input type="submit" value="Alterar" style="text-align:center;border:2px solid #804000;background-color:#F8F4E8;padding:3px;width:100%;" /> 
		</td>
	</tr>
</table>

<h4>* Exeções</h4>
<p><i>na</i> = Não modificar</p>

<h4>Outras Opções</h5>
<a href="javascript:set_maxstage()">&raquo; Todos Edifícios No Nível Máximo</a><br />
<a href="javascript:set_all_na()">&raquo; Não Alterar Nenhum Edifício</a>
</form>

<script type="text/javascript">
<!--

/**
 * JavaScript Functions generated by village_editor eXtension 
 */

{literal}
function set_maxstage() {
{/literal}

{foreach from=$max_lvl item=level key=dname}
	document.getElementById('{$dname}').value = {$level};
{/foreach}

{literal}
}
{/literal}

{literal}
function set_all_na() {
{/literal}

{foreach from=$max_lvl item=level key=dname}
	document.getElementById('{$dname}').value = "na";
{/foreach}

{literal}
}
{/literal}
//-->
</script>

<!--  
Debugger:
{$v_debug}
-->